<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\SingSiamOld\Logfile202504.cs" />
    <Compile Remove="Models\SingSiamOld\Logfile202505.cs" />
    <Compile Remove="Models\SingSiamOld\ZzLogfile.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Ccv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cdv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cev.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cfv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cgv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Chv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Civ.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Ckv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Clv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cmv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cnv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Cpv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Pav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw0Pbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Ccv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cdv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cev.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cfv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cgv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Chv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Civ.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cjv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Ckv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Clv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cmv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cnv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cov.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cpv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Cqv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Pav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Pbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Pcv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Y.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Zv1.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw1Zv2.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Ccv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cdv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cev.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cfv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cgv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Chv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Civ.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cjv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Ckv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Clv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cmv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cnv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cov.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cpv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Cqv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Pav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Pbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Pcv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Y.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Zv1.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw2Zv2.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Ccv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cdv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cev.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cfv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cgv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Chv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Civ.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cjv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Ckv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Clv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cmv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cnv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cov.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cpv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Cqv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Pav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Pbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Pcv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Y.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Zv1.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw3Zv2.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Ccv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cdv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cev.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cfv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cgv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Chv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Civ.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cjv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Ckv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Clv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cmv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cnv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cov.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cpv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Cqv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Pav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Pbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Pcv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Y.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Zv1.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw4Zv2.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cav.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cbv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Ccv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cdv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cev.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cfv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cgv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Chv.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Civ.cs" />
    <Compile Remove="Models\SingSiamOld\ZzRaw5Cjv.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Shared\SlipLayout.razor" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.16">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MudBlazor" Version="6.15.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
    <PackageReference Include="System.Diagnostics.Tools" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\customers\" />
    <Folder Include="wwwroot\img\Land\" />
    <Folder Include="wwwroot\img\branch\" />
    <Folder Include="wwwroot\img\Employee\" />
    <Folder Include="wwwroot\img\vehicle\" />
    <Folder Include="wwwroot\font\" />
  </ItemGroup>

  <ItemGroup>
    <UpToDateCheckInput Remove="Shared\SlipLayout.razor" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Shared\SlipLayout.razor" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Shared\SlipLayout.razor" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoGenReports\AutoGenReports.csproj" />
  </ItemGroup>

</Project>
